package com.example.databindingjavasample;

import android.os.Bundle;

import androidx.appcompat.app.AppCompatActivity;
import androidx.databinding.DataBindingUtil;

import com.example.databindingjavasample.dataBindingModel.MainActivityData;
import com.example.databindingjavasample.databinding.ActivityMainBinding;

/**
 * 1. Enable data binding in app gradle module
 * 2. Wrap layout inside <layout> </layout> tag
 * 3. Data is declared inside the <data> </data> block and the data model class will define in <variable> </variable> tag
 *      3.1 Create the object for the model class, then set it with <variable>
 * 4. in DataBindingFragment class define how to implement databinding in fragments*/

public class MainActivity extends AppCompatActivity {

    //This binding object is like a layer of glue between layout and its views, data
    // ActivityMainBinding name is derived from the name of the xml layout, This is generated by the compiler
    private ActivityMainBinding binding;
    private MainActivityData mainActivityData = new MainActivityData();

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        /**Replace the setContentView() with DataBindingUtil.setContentView()*/
        binding = DataBindingUtil.setContentView(this,R.layout.activity_main);
        binding.setMainActivityData(mainActivityData); /**we set the value for the <variable> "mainActivityData" which we declared in xml layout */

        binding.helloWorld.setText("hello,"); //without data binding, binding.helloWorld - > replaces the findViewById()
        mainActivityData.setWelcome("welcome Eldho"); // Data Binding
    }
}
